name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    
    - name: Checkout blog sources
      uses: actions/checkout@v2

    - name: Checkout deploy repo
      uses: actions/checkout@v2
      with:
        repository: thisdk/thisdk.github.io
        ref: master
        path: .deploy_git

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Config git environment
      env:
        HEXO_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name thisdk
        git config --global user.email thisdk@gmail.com

    - name: Install & Deploy
      run: |
        npm install hexo-cli -g
        npm install
        hexo deploy
